name: ci
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build for Windows
        if: ${{ matrix.os == 'windows-2022' }}
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -B build -G "NMake Makefiles"
          cmake --build build
      - name: Build for Linux
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          cmake -B build
          cmake --build build
      - name: Build for macOS
        if: ${{ matrix.os == 'macos-12' }}
        run: |
          cmake -B build
          cmake --build build
      - name: Run
        run: node src/main.js
